messages:
  start: "Привет, я ваш личный учётник.\nЯ помогу вам вести контроль ваших растрат."
  expenses: "У вас пока нет записанных расходов"
  support: "Вы хотите обратиться в поддержку?"
  idea: "Напишите свои идеи и предложения!
  Поделитесь с нами своими идеями. Мы учтём все пожелания или решим вашу проблему с которой вы столкнулись!"
  FAQ: "Вы когда-нибудь задумывались куда уходят ваши деньги? 🤔
  Думаю да, но вам всегда казалось, что вы никаких лишних трат не делаете, что вы тратите всё разумно и каждая трата делается обоснованно.
  Но попробуйте это всё записать на бумаге и проанализировать, вы поймёте что очень много расходов вы делаете впустую и они были абсолютно не нужны.
  С помощью этого бота, бумага или блокнот вам не потребуется.
  Нажмите на кнопку Расходы и ведите контроль своих трат.
  Удачи вам на пути реализации задуманного и легкости в достижении целей! 🤗"